name = "picowi"
description = "Standalone WiFi driver for the Pi Pico-W in Ada"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
licenses = "MIT"
website = ""
tags = []

executables = ["picowi"]

[build-switches]
development.optimization = ["-O0"]

[[depends-on]]
rp2040_hal = "^2.5.0"
pico_bsp = "^2.2.0"

[[pins]]
rp2040_hal = { url='https://github.com/JeremyGrosser/rp2040_hal' }

